// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhSaDK9CccznusICbQRqw6w8IAqzRGr2M',
    appId: '1:75051611706:web:app_id_placeholder',
    messagingSenderId: '75051611706',
    projectId: 'topgrade-a7a00',
    authDomain: 'topgrade-a7a00.firebaseapp.com',
    storageBucket: 'topgrade-a7a00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhSaDK9CccznusICbQRqw6w8IAqzRGr2M',
    appId: '1:75051611706:android:b0b1ad1ab4cbb7fcd26703',
    messagingSenderId: '75051611706',
    projectId: 'topgrade-a7a00',
    storageBucket: 'topgrade-a7a00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5iyQgz9JKc15erC3fmGU2kw6GDUtwc4g',
    appId: '1:75051611706:ios:e26f5cd750cce98ad26703',
    messagingSenderId: '75051611706',
    projectId: 'topgrade-a7a00',
    storageBucket: 'topgrade-a7a00.firebasestorage.app',
    iosBundleId: 'com.topgrade.app',
  );
}
